services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: customer_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: customer_insights
    ports:
      - "5432:5432"      

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://customer_user:password123@db:5432/customer_insights
    depends_on:
      - db
    command: /wait-for-it.sh db:5432 -- uvicorn main:app --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
